# Generated by Django 4.1.4 on 2023-07-06 06:40

import builtins
import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('text', models.TextField()),
                ('creat_date', models.DateField(default=datetime.datetime(2023, 7, 6, 6, 40, 21, 394205, tzinfo=datetime.timezone.utc))),
                ('puplished_date', models.DateField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=builtins.any, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=500)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=datetime.datetime(2023, 7, 6, 6, 40, 21, 394205, tzinfo=datetime.timezone.utc))),
                ('approved_comment', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=builtins.any, related_name='comments', to='blog_app.post')),
            ],
        ),
    ]
