# Generated by Django 4.1.4 on 2023-07-06 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='puplished_date',
            new_name='published_date',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 6, 6, 53, 42, 522019, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='creat_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 6, 6, 53, 42, 522019, tzinfo=datetime.timezone.utc)),
        ),
    ]
