# Generated by Django 4.1.4 on 2023-07-06 11:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_rename_puplished_date_post_published_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='creat_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
